[build]
    publish = "out/"
    command = "npm run deploy"

[context.production]
  environment = { NODE_VERSION = "16.13.0" }

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin= "pedromarquez.dev, pfernandom.github.io"

[[headers]]
    for = "/rss.xml"
    [headers.values]
        Access-Control-Allow-Origin= "*"