/**
 * Autogenerated by scripts/jsonschema.ts
 **/
export const schema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  properties: {
    date: { id: "http://example.com/date", type: "string" },
    description: {
      oneOf: [{ items: { type: "string" }, type: "array" }, { type: "string" }],
    },
    hero_height: { type: "number" },
    hero_image: { type: "string" },
    hero_image_alt: { type: "string" },
    hero_image_blur: { type: "string" },
    hero_image_original: { type: "string" },
    hero_width: { type: "number" },
    key_words: {
      oneOf: [{ items: { type: "string" }, type: "array" }, { type: "string" }],
    },
    legacy: { type: "boolean" },
    published: { type: "boolean" },
    series: { type: "string" },
    slug: { id: "http://example.com/slug", type: "string" },
    social_footer: { type: "string" },
    social_subtitle: { type: "string" },
    social_title: { type: "string" },
    subblog_slug: { type: "string" },
    test: { type: "boolean" },
    title: { type: "string" },
  },
  type: "object",
  required: ["title", "description", "date"],
};

export type Post = {
  date: string;
  description: string[] | string;
  hero_height?: number;
  hero_image?: string;
  hero_image_alt?: string;
  hero_image_blur?: string;
  hero_image_original?: string;
  hero_width?: number;
  key_words?: string[] | string;
  legacy?: boolean;
  published?: boolean;
  series?: string;
  slug?: string;
  social_footer?: string;
  social_subtitle?: string;
  social_title?: string;
  subblog_slug?: string;
  test?: boolean;
  title: string;
};
